import React, { useState } from 'react';
import "../styles.css"; 

const SupportPage = () => {
  const [activeIndex, setActiveIndex] = useState(-1);

  const handleToggle = index => {
    setActiveIndex(activeIndex === index ? -1 : index);
  };

  return (
    <div className="support-page">
      <div className="faq-container">
        <h2>Frequently Asked Questions</h2>
        <div className="accordion">
          <div className="accordion-item" onClick={() => handleToggle(0)}>
            <div className="accordion-title">How do I reset my password?</div>
            {activeIndex === 0 && (
              <div className="accordion-content">
                You can reset your password by going to your account settings and selecting 'Reset Password'.
              </div>
            )}
          </div>
          <div className="accordion-item" onClick={() => handleToggle(1)}>
            <div className="accordion-title">Where can I view my financial reports?</div>
            {activeIndex === 1 && (
              <div className="accordion-content">
                Your financial reports can be found in the 'Reports' section of the dashboard.
              </div>
            )}
          </div>
          <div className="accordion-item" onClick={() => handleToggle(2)}>
            <div className="accordion-title">How does FinOptiX use machine learning to enhance financial decision-making?</div>
            {activeIndex === 2 && (
              <div className="accordion-content">
                FinOptiX utilizes machine learning algorithms to analyze historical financial data and market trends. This analysis helps predict future financial conditions and make prescriptive recommendations, thereby enhancing decision-making for small to medium-sized enterprises.
              </div>
            )}
          </div>
          <div className="accordion-item" onClick={() => handleToggle(3)}>
            <div className="accordion-title">Can I customize the financial reports generated by FinOptiX?</div>
            {activeIndex === 3 && (
              <div className="accordion-content">
                Yes, FinOptiX allows users to customize their financial reports. You can choose which data points to include and how to visualize them, tailoring the reports to meet your specific business needs.
              </div>
            )}
          </div>
          <div className="accordion-item" onClick={() => handleToggle(4)}>
            <div className="accordion-title">How can I integrate FinOptiX with other business tools and platforms?</div>
            {activeIndex === 4 && (
              <div className="accordion-content">
                FinOptiX offers robust API integration capabilities, allowing it to seamlessly connect with various business tools and platforms such as CRM systems, ERP software, and other financial management tools. This integration enhances data synchronization and provides a more comprehensive overview of your business operations.
              </div>
            )}
          </div>
        </div>
      </div>
      <div className="contact-container">
        <h2>Contact Us</h2>
        <form className="contact-form">
          <input type="text" placeholder="Your Name" className="form-input" />
          <input type="email" placeholder="Your Email" className="form-input" />
          <textarea placeholder="Your Message" className="form-textarea"></textarea>
          <button type="submit" className="form-button">Send</button>
        </form>
      </div>
    </div>
  );
};

export default SupportPage;
